# Permalinks
permalink: pretty

title: Thesis Studio
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  documentation of thesis studio work. very much WIP.
baseurl: "/ts1" # the subpath of your site, e.g. /blog
url: "https://burnedsap.github.io/ts"
twitter_username: burnedsap
github_username:  burnedsap

# Build settings
plugins:
  - jekyll-feed
